### ISSUE TITLE
Upload csv to backendvia http service 

### ISSUE THREAD

**Issue by tarunprakashsingh** [basecss/fileInput#4]
Hello
I need to upload cav file to the backend http service, was hoping to use some of your code... i am new to react just few weeks in to it. If you could help me how and what i need to add/change here to get it working. Your help will be very valuable to me.
Thanks for the help in advance.
Tarun

**Comment by basecss** [comment]
@tarunprakashsingh 

Sorry, I'm offline too long.

Just need to remove/disable `files.filter` or modify the `_onChange` method to support more file type.
